### ISSUE TITLE
[init] 수정된 yml에 맞게 동작하는 SpringBootTest 코드 짜기

### ISSUE THREAD

**Issue by proLmpa** [proLmpa/NBC_2tWasSummer#53]
* Mockito 테스트 코드 구현 포기 -> @SpringBootTest 통합 테스트 코드 구축으로 변경

**Comment by JisooPyo** [comment]
Deck은 Mockito로 테스트를 하는 게 너무 어려울 것 같아서 최대한 CI를 Spring Boot Test가 되는 방향으로 짜오겠습니다..

**Comment by JisooPyo** [comment]
끄앙 왜 Login이 안 되는 것인가!!!!!!

```java
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.springframework.aop.framework.AdvisedSupport.getInterceptorsAndDynamicInterceptionAdvice(AdvisedSupport.java:483)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:228)
	at jdk.proxy3/jdk.proxy3.$Proxy194.authenticate(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:237)
```
